### PR TITLE
WIP. Support Amazon S3 FileSystem.

### PR DESCRIPTION
**Pull request by rulle-io**
Requires more testing. Works locally in IDEA.
Related to #209 .

### CODE REVIEW

**Comment by pan-xuan** [comment]
why did we not merge this pr?

**Comment by ra1861** [comment]
I have not managed to make integration tests to work (in time). Will continue working on this during next available timeslot. ;)

**Comment by pan-xuan** [comment]
understand. understand. Looking forward to it. Is it during a hack day interval? We'd like to understand if we can have it out in our next release cycle.

**Comment by tfoldi** [comment]
first of all, thanks for the patch: dbeam is used in production with S3 targets at one of my large client. Is there anything I can help with to get it merged? adding tests or docuemtation? thx /cc @rulle-io

**Comment by rulle-io** [comment]
Sorry, I got involved in other things and forgot about it. :) I will create a proper PR in coming days.

**Comment by pan-xuan** [comment]
I also forgot about this. You rock Ruslan. Looking forward to include this in our next release

**Comment by tfoldi** [comment]
> Technically, I wanted to add a e2e test to see that iy actually works.
> If you can add such one, it would simplify things a lot. @tfoldi

I can do the e2e tests, no issues. Do we want to use a real S3 bucket or just a mocked S3 service? If you want the real thing, we might need to set up access/secret keys for the CI.

**Comment by rulle-io** [comment]
Just a mocked S3 service, please.

**Comment by tfoldi** [comment]
How about this: https://github.com/rulle-io/dbeam/pull/1/commits/6647bb84e1dd9362ed9e2542ac496cc93ac53eb9 ?

**Comment by kellen** [comment]
Closing as stale

**Pull request closed without merging**
